apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "reference-app-orders-go.fullname" . }}-main-worker
  labels:
    {{- include "reference-app-orders-go.labels" (list . "main-worker") | nindent 4 }}
spec:
  replicas: {{ .Values.main.worker.replicaCount }}
  selector:
    matchLabels:
      {{- include "reference-app-orders-go.selectorLabels" (list . "main-worker") | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "reference-app-orders-go.labels" (list . "main-worker") | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: {{ .Chart.Name }}-main-worker
          image: "{{ .Values.main.worker.image.repository }}:{{ .Values.main.worker.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          args:
            {{- if .Values.encryptionKeyID }}
            - "-k"
            - {{ .Values.encryptionKeyID }}
            {{- end }}
            - "-s"
            - "order,shipment"
          {{- if .Values.metrics.enabled }}
          ports:
            - name: metrics
              containerPort: {{ .Values.metrics.port }}
              protocol: TCP
          {{- end }}
          env:
            - name: TEMPORAL_ADDRESS
              value: {{ .Values.temporal.address | quote }}
            - name: TEMPORAL_NAMESPACE
              value: {{ .Values.temporal.namespace | quote }}
            {{- if .Values.metrics.enabled }}
            - name: TEMPORAL_METRICS_ENDPOINT
              value: "0.0.0.0:{{ .Values.metrics.port }}"
            {{- end }}
            - name: BILLING_API_URL
              value: "http://{{ include "reference-app-orders-go.fullname" . }}-billing-api:{{ .Values.services.billing.port }}"
            - name: ORDER_API_URL
              value: "http://{{ include "reference-app-orders-go.fullname" . }}-main-api:{{ .Values.services.order.port }}"
            - name: SHIPMENT_API_URL
              value: "http://{{ include "reference-app-orders-go.fullname" . }}-main-api:{{ .Values.services.shipment.port }}"
          resources:
            {{- toYaml .Values.main.worker.resources | nindent 12 }} 