{{- if gt (.Values.main.api.replicaCount | int) 1 }}
{{- fail "main.api.replicaCount cannot be greater than 1 until database support is implemented. Please set main.api.replicaCount to 1." }}
{{- end }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "reference-app-orders-go.fullname" . }}-main-api
  labels:
    {{- include "reference-app-orders-go.labels" (list . "main-api") | nindent 4 }}
spec:
  replicas: {{ .Values.main.api.replicaCount }}
  selector:
    matchLabels:
      {{- include "reference-app-orders-go.selectorLabels" (list . "main-api") | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "reference-app-orders-go.labels" (list . "main-api") | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: {{ .Chart.Name }}-main-api
          image: "{{ .Values.main.api.image.repository }}:{{ .Values.main.api.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          args:
            {{- if .Values.encryptionKeyID }}
            - "-k"
            - {{ .Values.encryptionKeyID }}
            {{- end }}
            - "-s"
            - "order,shipment,fraud"
          ports:
            - name: order
              containerPort: {{ .Values.services.order.port }}
              protocol: TCP
            - name: shipment
              containerPort: {{ .Values.services.shipment.port }}
              protocol: TCP
            - name: fraud
              containerPort: {{ .Values.services.fraud.port }}
              protocol: TCP
            {{- if .Values.metrics.enabled }}
            - name: metrics
              containerPort: {{ .Values.metrics.port }}
              protocol: TCP
            {{- end }}
          env:
            - name: TEMPORAL_ADDRESS
              value: {{ .Values.temporal.address | quote }}
            - name: TEMPORAL_NAMESPACE
              value: {{ .Values.temporal.namespace | quote }}
            {{- if .Values.metrics.enabled }}
            - name: TEMPORAL_METRICS_ENDPOINT
              value: "0.0.0.0:{{ .Values.metrics.port }}"
            {{- end }}
            - name: ORDER_API_PORT
              value: {{ .Values.services.order.port | quote }}
            - name: SHIPMENT_API_PORT
              value: {{ .Values.services.shipment.port | quote }}
            - name: FRAUD_API_PORT
              value: {{ .Values.services.fraud.port | quote }}
          resources:
            {{- toYaml .Values.main.api.resources | nindent 12 }} 