apiVersion: v1
kind: Service
metadata:
  name: {{ include "reference-app-orders-go.fullname" . }}-mongodb
  labels:
    {{- include "reference-app-orders-go.labels" (list . "mongodb") | nindent 4 }}
spec:
  ports:
    - name: mongodb
      port: 27017
      targetPort: 27017
  selector:
    {{- include "reference-app-orders-go.selectorLabels" (list . "mongodb") | nindent 4 }}
