apiVersion: v1
kind: Service
metadata:
  name: {{ include "reference-app-orders-go.fullname" . }}-web
  labels:
    {{- include "reference-app-orders-go.labels" (list . "web") | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 80
      targetPort: 3000
  selector:
    {{- include "reference-app-orders-go.selectorLabels" (list . "web") | nindent 4 }} 