{{- if .Values.metrics.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "reference-app-orders-go.fullname" . }}-main-worker
  labels:
    {{- include "reference-app-orders-go.labels" (list . "main-worker") | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - name: metrics
      port: {{ .Values.metrics.port }}
      targetPort: {{ .Values.metrics.port }}
  selector:
    {{- include "reference-app-orders-go.selectorLabels" (list . "main-worker") | nindent 4 }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "reference-app-orders-go.fullname" . }}-billing-worker
  labels:
    {{- include "reference-app-orders-go.labels" (list . "billing-worker") | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - name: metrics
      port: {{ .Values.metrics.port }}
      targetPort: {{ .Values.metrics.port }}
  selector:
    {{- include "reference-app-orders-go.selectorLabels" (list . "billing-worker") | nindent 4 }}
{{- end }} 