apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/component: billing-api
    app.kubernetes.io/name: oms
  name: oms-billing-api
  namespace: oms
spec:
  ports:
    - name: "8081"
      port: 8081
      targetPort: 8081
    - name: "8084"
      port: 8084
      targetPort: 8084
  selector:
    app.kubernetes.io/component: billing-api
    app.kubernetes.io/name: oms
