apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/component: main-worker
    app.kubernetes.io/name: oms
  name: oms-main-worker
  namespace: oms
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/component: main-worker
      app.kubernetes.io/name: oms
  template:
    metadata:
      labels:
        app.kubernetes.io/component: main-worker
        app.kubernetes.io/name: oms
    spec:
      containers:
        - args:
            - -k
            - supersecretkey
            - -s
            - order,shipment
          env:
            - name: BILLING_API_URL
              value: http://billing-api:8081
            - name: ORDER_API_URL
              value: http://main-api:8082
            - name: SHIPMENT_API_URL
              value: http://main-api:8083
            - name: TEMPORAL_ADDRESS
              value: temporal-frontend.temporal:7233
          image: ghcr.io/temporalio/reference-app-orders-go-worker:latest
          name: main-worker
          imagePullPolicy: Always
      enableServiceLinks: false
