apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/component: main-api
    app.kubernetes.io/name: oms
  name: oms-main-api
  namespace: oms
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/component: main-api
      app.kubernetes.io/name: oms
  template:
    metadata:
      labels:
        app.kubernetes.io/component: main-api
        app.kubernetes.io/name: oms
    spec:
      containers:
        - args:
            - -k
            - supersecretkey
            - -s
            - order,shipment
          env:
            - name: BIND_ON_IP
              value: 0.0.0.0
            - name: MONGO_URL
              value: mongodb://mongo:27017
            - name: ORDER_API_PORT
              value: "8082"
            - name: SHIPMENT_API_PORT
              value: "8083"
            - name: TEMPORAL_ADDRESS
              value: temporal-frontend.temporal:7233
          image: ghcr.io/temporalio/reference-app-orders-go-api:latest
          name: main-api
          ports:
            - containerPort: 8082
              protocol: TCP
            - containerPort: 8083
              protocol: TCP
          imagePullPolicy: Always
      enableServiceLinks: false
